#!/usr/bin/env bash
# :)
CONTADOR=0
STOP=9
while [ $STOP -ge $CONTADOR ]
    do
      echo "Best School"
      if [ $CONTADOR -eq 8 ]
      then
	      echo "Hi"
      fi
      ((CONTADOR++))
   done
