#!/usr/bin/env bash
# ;)
CONTADOR=1
STOP=20
while [ $STOP -ge $CONTADOR ]
    do
	    case $CONTADOR in
		    5) 
			    echo "bad luck from China"
			    ;;
		    10)
			    echo "bad luck from Japan"
			    ;;
		    18)
			    echo "bad luck from Italy"
			    ;;
	    esac
	    echo $CONTADOR
      ((CONTADOR++))
   done
