#!/usr/bin/env bash
#  try whit case
case $1 in
	start)
		./manage_my_process &
		echo "$!" >> /var/run/my_process.pid
		echo "manage_my_process started"
		;;
	stop)
                rm -r /var/run/my_process.pid
		pkill -20 -f ./manage_my_process
		echo "manage_my_process stopped"
		;;
	restart)
                rm -r /var/run/my_process.pid
                pkill -20 -f ./manage_my_process
                ./manage_my_process &
                echo "$!" >> /var/run/my_process.pid
		echo "manage_my_process restarted"
		;;
	*)
		echo 'Usage: manage_my_process {start|stop|restart}'
		;;
esac
